/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Phonetic: typeof import('./components/Phonetic.vue')['default']
    Ruby: typeof import('./components/Ruby.vue')['default']
  }
}
